const C=window.QUIXPRINT_CRM_CONFIG||{},configured=C.SUPABASE_URL&&!C.SUPABASE_URL.includes("YOUR_")&&C.SUPABASE_ANON_KEY&&!C.SUPABASE_ANON_KEY.includes("YOUR_");
const db=configured?window.supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY):null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const stages=["New Lead","Researching","Contacted","Follow-Up","Quoted","Won","Lost"];
const S={user:null,workspace:null,members:[],leads:[],activities:[],currentLead:null};
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const today=()=>{let d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const money=v=>Number(v||0).toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0});
const fmt=v=>v?new Date(v+"T12:00:00").toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"}):"—";
const member=id=>S.members.find(x=>x.user_id===id)?.display_name||"Unassigned";
function toast(m,e=false){let t=$("#toast");t.textContent=m;t.className="toast show"+(e?" error":"");setTimeout(()=>t.className="toast",2600)}
function authTabs(){$$("[data-auth]").forEach(b=>b.onclick=()=>{$$("[data-auth]").forEach(x=>x.classList.toggle("active",x===b));$("#loginForm").classList.toggle("hidden",b.dataset.auth!=="login");$("#signupForm").classList.toggle("hidden",b.dataset.auth!=="signup")})}
async function init(){authTabs();fillStages();if(!configured){$("#configWarning").classList.remove("hidden");return}const {data:{session}}=await db.auth.getSession();if(session)await enter(session.user);db.auth.onAuthStateChange(async(_,s)=>{if(s&&!S.user)await enter(s.user)})}
function fillStages(){$("#stage").innerHTML=stages.map(x=>`<option>${x}</option>`).join("");$("#stageFilter").innerHTML='<option value="">All stages</option>'+stages.map(x=>`<option>${x}</option>`).join("")}
$("#loginForm").onsubmit=async e=>{e.preventDefault();let {error}=await db.auth.signInWithPassword({email:$("#loginEmail").value.trim(),password:$("#loginPassword").value});if(error)toast(error.message,true)}
$("#signupForm").onsubmit=async e=>{e.preventDefault();let code=$("#joinCode").value.trim().toUpperCase(),{data,error}=await db.auth.signUp({email:$("#signupEmail").value.trim(),password:$("#signupPassword").value,options:{data:{display_name:$("#signupName").value.trim()}}});if(error)return toast(error.message,true);if(!data.session)return toast("Check your email to confirm your account, then log in.");if(code){let {error:x}=await db.rpc("join_workspace",{invite_code_input:code});if(x)return toast(x.message,true)}await enter(data.user)}
async function enter(u){S.user=u;$("#authView").classList.add("hidden");$("#appView").classList.remove("hidden");await Promise.all([loadWorkspace()]);await Promise.all([loadMembers(),loadLeads(),loadActivities()]);bind();render()}
async function loadWorkspace(){let {data,error}=await db.from("workspace_members").select("workspace_id,workspaces(id,name,invite_code)").eq("user_id",S.user.id).single();if(error)return toast(error.message,true);S.workspace=data.workspaces}
async function loadMembers(){let {data,error}=await db.from("workspace_members").select("*").eq("workspace_id",S.workspace.id).order("created_at");if(error)return toast(error.message,true);S.members=data||[];let opts='<option value="">Unassigned</option>'+S.members.map(m=>`<option value="${m.user_id}">${esc(m.display_name||m.email)}</option>`).join("");$("#owner").innerHTML=opts;$("#ownerFilter").innerHTML='<option value="">All owners</option>'+opts.replace('<option value="">Unassigned</option>','')}
async function loadLeads(){let {data,error}=await db.from("leads").select("*").eq("workspace_id",S.workspace.id).order("updated_at",{ascending:false});if(error)return toast(error.message,true);S.leads=data||[]}
async function loadActivities(){let {data,error}=await db.from("activities").select("*").eq("workspace_id",S.workspace.id).order("activity_date",{ascending:false}).order("created_at",{ascending:false}).limit(250);if(error)return toast(error.message,true);S.activities=data||[]}
let bound=false;function bind(){if(bound)return;bound=true;$$(".nav[data-view]").forEach(b=>b.onclick=()=>view(b.dataset.view));$("#logoutBtn").onclick=()=>db.auth.signOut().then(()=>location.reload());$("#addLeadBtn").onclick=()=>openLead();$("#quickCallBtn").onclick=openQuick;$("#closeLeadBtn").onclick=$("#cancelLeadBtn").onclick=()=>$("#leadDialog").close();$("#closeQuickBtn").onclick=()=>$("#quickActivityDialog").close();$("#leadForm").onsubmit=saveLead;$("#activityForm").onsubmit=saveActivity;$("#quickActivityForm").onsubmit=saveQuick;$("#deleteLeadBtn").onclick=deleteLead;["searchInput","stageFilter","ownerFilter","priorityFilter"].forEach(id=>$("#"+id).addEventListener(id==="searchInput"?"input":"change",renderLeads));$("#exportBtn").onclick=exportCSV;$("#copyCodeBtn").onclick=()=>navigator.clipboard.writeText(S.workspace.invite_code).then(()=>toast("Invite code copied."));$("#csvInput").onchange=importCSV;$$("[data-record-tab]").forEach(b=>b.onclick=()=>recordTab(b.dataset.recordTab))}
function view(n){$$(".view").forEach(x=>x.classList.add("hidden"));$("#"+n+"View").classList.remove("hidden");$$(".nav[data-view]").forEach(x=>x.classList.toggle("active",x.dataset.view===n));$("#pageTitle").textContent={dashboard:"Dashboard",pipeline:"Pipeline",leads:"All leads",followups:"Follow-ups",settings:"Settings"}[n];$("#addLeadBtn").classList.toggle("hidden",n==="settings")}
function render(){renderDashboard();renderPipeline();renderLeads();renderFollowups();renderSettings();refreshQuickOptions()}
function active(l){return !["Won","Lost"].includes(l.stage)}
function renderDashboard(){let due=S.leads.filter(l=>active(l)&&l.next_follow_up&&l.next_follow_up<=today()),open=S.leads.filter(active),won=S.leads.filter(l=>l.stage==="Won");$("#statTotal").textContent=S.leads.length;$("#statDue").textContent=due.length;$("#statPipeline").textContent=money(open.reduce((a,l)=>a+Number(l.estimated_value||0),0));$("#statWon").textContent=money(won.reduce((a,l)=>a+Number(l.estimated_value||0),0));let max=Math.max(...stages.map(s=>S.leads.filter(l=>l.stage===s).length),1);$("#funnel").innerHTML=stages.map(s=>{let n=S.leads.filter(l=>l.stage===s).length;return `<div class="funnel-row"><span>${s}</span><div class="bar"><i style="width:${n/max*100}%"></i></div><strong>${n}</strong></div>`}).join("");let pri=[...due].sort(sortLead).slice(0,7);$("#priorityList").innerHTML=list(pri,l=>`${l.priority} · ${fmt(l.next_follow_up)}`,"Nothing urgent today.");$("#recentList").innerHTML=list(S.leads.slice(0,7),l=>`${l.stage} · ${member(l.owner_id)}`,"No leads yet.");$("#recentActivity").innerHTML=S.activities.slice(0,7).map(a=>{let l=S.leads.find(x=>x.id===a.lead_id);return `<div class="list-item"><div><strong>${esc(a.activity_type)}: ${esc(a.subject)}</strong><small>${esc(l?.company||"Deleted lead")}</small></div><small>${fmt(a.activity_date)}</small></div>`}).join("")||'<div class="empty">No activity yet.</div>'}
function sortLead(a,b){let p={Hot:0,Warm:1,Normal:2,Low:3};return (p[a.priority]-p[b.priority])||String(a.next_follow_up||"9999").localeCompare(String(b.next_follow_up||"9999"))}
function list(items,sub,empty){return items.length?items.map(l=>`<div class="list-item"><div><strong>${esc(l.company)}</strong><small>${esc(l.contact_name||l.products||"No contact")}</small></div><div><span>${esc(sub(l))}</span><small>${money(l.estimated_value)}</small></div></div>`).join(""):`<div class="empty">${empty}</div>`}
function renderPipeline(){$("#kanban").innerHTML=stages.map(s=>{let rows=S.leads.filter(l=>l.stage===s).sort(sortLead);return `<section class="kanban-col"><div class="kanban-head"><h3>${s}</h3><strong>${rows.length}</strong></div>${rows.map(l=>`<article class="kanban-card" onclick="openLead('${l.id}')"><strong>${esc(l.company)}</strong><p>${esc(l.contact_name||"No contact")}</p><p>${esc(l.products||l.industry||"")}</p><div class="card-foot"><span class="priority ${l.priority}">${l.priority}</span><span>${fmt(l.next_follow_up)}</span></div><div class="card-foot"><span>${esc(member(l.owner_id))}</span><strong>${money(l.estimated_value)}</strong></div></article>`).join("")}</section>`}).join("")}
function filtered(){let q=$("#searchInput").value.toLowerCase(),st=$("#stageFilter").value,ow=$("#ownerFilter").value,pr=$("#priorityFilter").value;return S.leads.filter(l=>(!st||l.stage===st)&&(!ow||l.owner_id===ow)&&(!pr||l.priority===pr)&&(!q||[l.company,l.contact_name,l.email,l.phone,l.website,l.industry,l.location,l.products,l.notes,l.opportunity_summary].some(v=>String(v||"").toLowerCase().includes(q))))}
function renderLeads(){let rows=filtered();$("#emptyLeads").classList.toggle("hidden",!!rows.length);$("#leadRows").innerHTML=rows.map(l=>`<tr><td><strong>${esc(l.company)}</strong><br><small>${esc(l.industry||l.location||"")}</small></td><td>${esc(l.contact_name||"—")}<br><small>${esc(l.email||l.phone||"")}</small></td><td><span class="badge ${l.stage}">${l.stage}</span></td><td><span class="priority ${l.priority}">${l.priority}</span></td><td>${esc(member(l.owner_id))}</td><td>${fmt(l.next_follow_up)}</td><td>${money(l.estimated_value)}</td><td><button class="row-btn" onclick="openLead('${l.id}')">•••</button></td></tr>`).join("")}
function renderFollowups(){let a=S.leads.filter(l=>active(l)&&l.next_follow_up).sort((x,y)=>x.next_follow_up.localeCompare(y.next_follow_up)),t=today();$("#overdueList").innerHTML=list(a.filter(l=>l.next_follow_up<t),l=>fmt(l.next_follow_up),"Nothing overdue.");$("#todayList").innerHTML=list(a.filter(l=>l.next_follow_up===t),l=>l.priority,"Nothing due today.");$("#upcomingList").innerHTML=list(a.filter(l=>l.next_follow_up>t),l=>fmt(l.next_follow_up),"Nothing upcoming.")}
function renderSettings(){$("#workspaceCode").textContent=S.workspace.invite_code;$("#teamList").innerHTML=S.members.map(m=>`<div class="list-item"><div><strong>${esc(m.display_name||"Team member")}</strong><small>${esc(m.email)}</small></div><span>${esc(m.role)}</span></div>`).join("")}
window.openLead=id=>{let l=S.leads.find(x=>x.id===id);S.currentLead=l||null;$("#leadTitle").textContent=l?"Edit lead":"Add lead";$("#leadId").value=l?.id||"";let map={company:"company",website:"website",contactName:"contact_name",contactTitle:"contact_title",email:"email",phone:"phone",industry:"industry",location:"location",stage:"stage",priority:"priority",owner:"owner_id",source:"source",products:"products",estimatedValue:"estimated_value",lastContacted:"last_contacted",nextFollowUp:"next_follow_up",opportunitySummary:"opportunity_summary",notes:"notes"};Object.entries(map).forEach(([el,k])=>$("#"+el).value=l?.[k]??(el==="stage"?"New Lead":el==="priority"?"Normal":""));$("#owner").value=l?.owner_id||S.user.id;$("#deleteLeadBtn").classList.toggle("hidden",!l);recordTab("details");renderActivity();$("#leadDialog").showModal()}
function recordTab(n){$$("[data-record-tab]").forEach(b=>b.classList.toggle("active",b.dataset.recordTab===n));$("#detailsTab").classList.toggle("hidden",n!=="details");$("#activityTab").classList.toggle("hidden",n!=="activity")}
async function saveLead(e){e.preventDefault();let id=$("#leadId").value,p={workspace_id:S.workspace.id,company:$("#company").value.trim(),website:$("#website").value.trim()||null,contact_name:$("#contactName").value.trim()||null,contact_title:$("#contactTitle").value.trim()||null,email:$("#email").value.trim()||null,phone:$("#phone").value.trim()||null,industry:$("#industry").value.trim()||null,location:$("#location").value.trim()||null,stage:$("#stage").value,priority:$("#priority").value,owner_id:$("#owner").value||null,source:$("#source").value.trim()||null,products:$("#products").value.trim()||null,estimated_value:Number($("#estimatedValue").value)||null,last_contacted:$("#lastContacted").value||null,next_follow_up:$("#nextFollowUp").value||null,opportunity_summary:$("#opportunitySummary").value.trim()||null,notes:$("#notes").value.trim()||null,updated_by:S.user.id};let q=id?db.from("leads").update(p).eq("id",id).select().single():db.from("leads").insert(p).select().single(),{data,error}=await q;if(error)return toast(error.message,true);S.currentLead=data;$("#leadId").value=data.id;$("#deleteLeadBtn").classList.remove("hidden");await loadLeads();render();toast(id?"Lead updated.":"Lead added.")}
async function deleteLead(){if(!confirm("Delete this lead and its activity history?"))return;let {error}=await db.from("leads").delete().eq("id",$("#leadId").value);if(error)return toast(error.message,true);$("#leadDialog").close();await Promise.all([loadLeads(),loadActivities()]);render();toast("Lead deleted.")}
function renderActivity(){let enabled=!!S.currentLead;$("#activityDisabled").classList.toggle("hidden",enabled);$("#activityForm").classList.toggle("hidden",!enabled);$("#activityDate").value=today();let rows=S.activities.filter(a=>a.lead_id===S.currentLead?.id);$("#activityTimeline").innerHTML=rows.map(a=>`<article class="timeline-item"><h4>${esc(a.activity_type)} · ${esc(a.subject)}</h4><small>${fmt(a.activity_date)} · ${esc(member(a.created_by))}</small>${a.body?`<p>${esc(a.body)}</p>`:""}</article>`).join("")||'<div class="empty">No activity logged yet.</div>'}
async function saveActivity(e){e.preventDefault();if(!S.currentLead)return;let p={workspace_id:S.workspace.id,lead_id:S.currentLead.id,activity_type:$("#activityType").value,subject:$("#activitySubject").value.trim(),body:$("#activityBody").value.trim()||null,activity_date:$("#activityDate").value||today(),created_by:S.user.id};let {error}=await db.from("activities").insert(p);if(error)return toast(error.message,true);if(["Call","Email","Meeting"].includes(p.activity_type))await db.from("leads").update({last_contacted:p.activity_date,updated_by:S.user.id}).eq("id",S.currentLead.id);$("#activitySubject").value="";$("#activityBody").value="";await Promise.all([loadActivities(),loadLeads()]);render();renderActivity();toast("Activity logged.")}
function refreshQuickOptions(){$("#quickLead").innerHTML='<option value="">Select a lead</option>'+S.leads.map(l=>`<option value="${l.id}">${esc(l.company)}${l.contact_name?" — "+esc(l.contact_name):""}</option>`).join("")}
function openQuick(){$("#quickDate").value=today();$("#quickActivityDialog").showModal()}
async function saveQuick(e){e.preventDefault();let p={workspace_id:S.workspace.id,lead_id:$("#quickLead").value,activity_type:$("#quickType").value,subject:$("#quickSubject").value.trim(),body:$("#quickBody").value.trim()||null,activity_date:$("#quickDate").value||today(),created_by:S.user.id};let {error}=await db.from("activities").insert(p);if(error)return toast(error.message,true);if(["Call","Email","Meeting"].includes(p.activity_type))await db.from("leads").update({last_contacted:p.activity_date,updated_by:S.user.id}).eq("id",p.lead_id);$("#quickActivityDialog").close();$("#quickActivityForm").reset();await Promise.all([loadActivities(),loadLeads()]);render();toast("Activity logged.")}
function exportCSV(){let h=["company","contact_name","contact_title","email","phone","website","industry","location","stage","priority","owner","source","products","estimated_value","last_contacted","next_follow_up","opportunity_summary","notes"],q=v=>`"${String(v??"").replaceAll('"','""')}"`,csv=[h.join(","),...filtered().map(l=>h.map(k=>q(k==="owner"?member(l.owner_id):l[k])).join(","))].join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=`quixprint-leads-${today()}.csv`;a.click();URL.revokeObjectURL(a.href)}
function parseCSV(t){let rows=[],r=[],c="",quoted=false;for(let i=0;i<t.length;i++){let x=t[i],n=t[i+1];if(x=='"'&&quoted&&n=='"'){c+='"';i++}else if(x=='"')quoted=!quoted;else if(x==","&&!quoted){r.push(c);c=""}else if((x=="\n"||x=="\r")&&!quoted){if(x=="\r"&&n=="\n")i++;r.push(c);if(r.some(v=>v.trim()))rows.push(r);r=[];c=""}else c+=x}r.push(c);if(r.some(v=>v.trim()))rows.push(r);return rows}
async function importCSV(e){let f=e.target.files[0];if(!f)return;let rows=parseCSV(await f.text()),h=rows[0]?.map(x=>x.trim().toLowerCase());if(!h?.includes("company"))return toast("CSV must include a company column.",true);let allowed=["company","contact_name","contact_title","email","phone","website","industry","location","stage","priority","source","products","estimated_value","last_contacted","next_follow_up","opportunity_summary","notes"],records=rows.slice(1).map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]?.trim()||null]))).filter(x=>x.company).map(x=>({...Object.fromEntries(Object.entries(x).filter(([k])=>allowed.includes(k))),workspace_id:S.workspace.id,owner_id:S.user.id,updated_by:S.user.id,stage:stages.includes(x.stage)?x.stage:"New Lead",priority:["Hot","Warm","Normal","Low"].includes(x.priority)?x.priority:"Normal",estimated_value:x.estimated_value?Number(x.estimated_value):null}));let {error}=await db.from("leads").insert(records);if(error)return toast(error.message,true);e.target.value="";await loadLeads();render();toast(`${records.length} leads imported.`)}
init();